// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYvr4H-zI7Dge8wByeonrnOFpGEIedTPM',
    appId: '1:441065088110:web:ae15bbab82d0b23baff27f',
    messagingSenderId: '441065088110',
    projectId: 'app-pokemon-c4102',
    authDomain: 'app-pokemon-c4102.firebaseapp.com',
    databaseURL: 'https://app-pokemon-c4102-default-rtdb.firebaseio.com',
    storageBucket: 'app-pokemon-c4102.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQF6Rr2pm-2zfBAqfSGtGPl9Dk5F1ipKU',
    appId: '1:441065088110:android:d28fc0e90a342008aff27f',
    messagingSenderId: '441065088110',
    projectId: 'app-pokemon-c4102',
    databaseURL: 'https://app-pokemon-c4102-default-rtdb.firebaseio.com',
    storageBucket: 'app-pokemon-c4102.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYvr4H-zI7Dge8wByeonrnOFpGEIedTPM',
    appId: '1:441065088110:web:063503f4c66eea25aff27f',
    messagingSenderId: '441065088110',
    projectId: 'app-pokemon-c4102',
    authDomain: 'app-pokemon-c4102.firebaseapp.com',
    databaseURL: 'https://app-pokemon-c4102-default-rtdb.firebaseio.com',
    storageBucket: 'app-pokemon-c4102.firebasestorage.app',
  );
}
